/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveFolderIdRouteImport } from './routes/drive.$folderId'
import { Route as ApiDownloadTokenFilenameRouteImport } from './routes/api/download.$token.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveFolderIdRoute = DriveFolderIdRouteImport.update({
  id: '/drive/$folderId',
  path: '/drive/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadTokenFilenameRoute =
  ApiDownloadTokenFilenameRouteImport.update({
    id: '/api/download/$token/$filename',
    path: '/api/download/$token/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive/$folderId': typeof DriveFolderIdRoute
  '/api/download/$token/$filename': typeof ApiDownloadTokenFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive/$folderId': typeof DriveFolderIdRoute
  '/api/download/$token/$filename': typeof ApiDownloadTokenFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive/$folderId': typeof DriveFolderIdRoute
  '/api/download/$token/$filename': typeof ApiDownloadTokenFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drive/$folderId' | '/api/download/$token/$filename'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drive/$folderId' | '/api/download/$token/$filename'
  id: '__root__' | '/' | '/drive/$folderId' | '/api/download/$token/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveFolderIdRoute: typeof DriveFolderIdRoute
  ApiDownloadTokenFilenameRoute: typeof ApiDownloadTokenFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/$folderId': {
      id: '/drive/$folderId'
      path: '/drive/$folderId'
      fullPath: '/drive/$folderId'
      preLoaderRoute: typeof DriveFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$token/$filename': {
      id: '/api/download/$token/$filename'
      path: '/api/download/$token/$filename'
      fullPath: '/api/download/$token/$filename'
      preLoaderRoute: typeof ApiDownloadTokenFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveFolderIdRoute: DriveFolderIdRoute,
  ApiDownloadTokenFilenameRoute: ApiDownloadTokenFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
